kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # port forward 8200 on the host to 30200 on this node
  extraPortMappings:
  - containerPort: 30200
    hostPort: 8200
  - containerPort: 30201
    hostPort: 8080
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "127.0.0.1"
    # optional: set the protocol to one of TCP, UDP, SCTP.
    # TCP is the default
    protocol: TCP
