apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-app
  namespace: csi-app
  labels:
    app: csi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-app
  template:
    metadata:
      labels:
        app: csi-app
    spec:
      serviceAccountName: csi-app-sa
      containers:
      - name: webapp
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache openssl
          while true; do
            echo "=== Database Credentials from VSO CSI Driver (Static Secrets) ==="
            echo "Username: $(cat /secrets/static/static_secret_0_dbUsername)"
            echo "Password: $(cat /secrets/static/static_secret_0_dbPassword)"
            echo ""
            echo "=== PKI Certificate from VaultPKICertificate (Dynamic Secrets) ==="
            if [ -f /secrets/dynamic/tls/tls.crt ]; then
              openssl x509 -in /secrets/dynamic/tls/tls.crt -noout -text | grep -E "Subject:|Issuer:|Not Before:|Not After :|Serial Number:|DNS:"
              echo ""
              echo "=== PKI Private Key Info ==="
              openssl rsa -in /secrets/dynamic/tls/tls.key -noout -text | head -3
              echo ""
              echo "=== Certificate Verification ==="
              openssl x509 -in /secrets/dynamic/tls/tls.crt -noout -subject -issuer
            else
              echo "PKI certificate not yet available, waiting..."
            fi
            echo ""
            echo "=== All mounted static secrets /secrets/static ==="
            ls -la /secrets/static/
            echo ""
            echo "=== All mounted dynamic secrets /secrets/dynamic/tls ==="
            ls -la /secrets/dynamic/tls/
            echo ""
            echo "Waiting 10 minutes before next check... ($(date))"
            sleep 600
          done
        volumeMounts:
        - name: vso-csi-static
          mountPath: "/secrets/static"
          readOnly: true
        - name: vso-dynamic-tls
          mountPath: "/secrets/dynamic/tls"
          readOnly: true
      volumes:
      - name: vso-csi-static
        csi:
          driver: csi.vso.hashicorp.com
          readOnly: true
          volumeAttributes:
            csiSecretsName: "csi-demo"
            csiSecretsNamespace: "csi-app"
      - name: vso-dynamic-tls
        secret:
          secretName: tls-cert