apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: tls-cert
  namespace: csi-app
spec:
  vaultAuthRef: csi-auth
  mount: pki
  role: example-dot-com
  commonName: test.example.com
  # Certificate format (default: pem)
  format: pem
  # Revoke certificate in Vault when this resource is deleted
  revoke: true
  # Delete the destination Kubernetes Secret when this resource is deleted
  clear: true
  destination:
    create: true
    name: tls-cert
    type: kubernetes.io/tls
    transformation:
      # Exclude the _raw field from being mounted
      excludeRaw: true