apiVersion: secrets.hashicorp.com/v1beta1
kind: CSISecrets
metadata:
  name: csi-demo
  namespace: csi-app
spec:
  vaultAuthRef:
    name: csi-auth
  namespace: tn001
  accessControl:
    serviceAccountPattern: shared-app-sa
    namespacePatterns:
      - csi-app
    podNamePatterns:
      - "^csi-app-*"
  secrets:
    vaultStaticSecrets:
      - mount: kvv2
        path: db-creds
        type: kv-v2
        transformation:
          excludes:
            - .*
          templates:
            dbUsername:
              text: "{{ .Secrets.username }}"
            dbPassword:
              text: "{{ .Secrets.password }}"
  syncConfig:
    containerState:
      namePattern: "^example$"