---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: vault-agent-app
data:
  vault-agent-init.hcl: |
    pid_file = "/home/vault/.pid"
    exit_after_auth = true

    vault {
      address = "http://vault.vault.svc.cluster.local:8200"
      namespace = "tn001"
    }

    auto_auth {
      method "jwt" {
        mount_path = "auth/k8s-auth-mount"
        config = {
          role = "vault-agent-secret"
          path = "/var/run/secrets/jwt-token"
          remove_jwt_after_reading = false
        }
      }
    }

    template {
      destination = "/vault/secrets/config.txt"
      contents = <<-EOT
      {{- with secret "kvv2/data/webapp/config" }}
      USERNAME={{ .Data.data.username }}
      PASSWORD={{ .Data.data.password }}
      {{- end }}
      EOT
    }

  vault-agent-sidecar.hcl: |
    pid_file = "/home/vault/.pid"
    exit_after_auth = false

    vault {
      address = "http://vault.vault.svc.cluster.local:8200"
      namespace = "tn001"
    }

    auto_auth {
      method "jwt" {
        mount_path = "auth/k8s-auth-mount"
        config = {
          role = "vault-agent-secret"
          path = "/var/run/secrets/jwt-token"
          remove_jwt_after_reading = false
        }
      }
    }

    template_config {
      static_secret_render_interval = "30s"
    }

    template {
      destination = "/vault/secrets/config.txt"
      contents = <<-EOT
      {{- with secret "kvv2/data/webapp/config" }}
      USERNAME={{ .Data.data.username }}
      PASSWORD={{ .Data.data.password }}
      {{- end }}
      EOT
    }
