apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-gcp-key
  namespace: gcp
spec:
  # Mount path of the secrets backend
  mount: gcp
  namespace: us-west-org
  # Path to the secret
  path: roleset/${PROJECT_ID}-viewer-key/key

  # Where to store the secrets, VSO will create the secret
  destination:
    create: true
    name: vso-gcp-key
    transformation:
      templates:
        private_key_data:
          text: |-
            {{- printf (get .Secrets "private_key_data" | b64dec ) -}}

#  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: gcp-app
#
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: gcp-dynamic-auth
#  params:
#    ttl: "1m"

#---
#apiVersion: secrets.hashicorp.com/v1beta1
#kind: VaultDynamicSecret
#metadata:
#  name: vso-gcp-token
#  namespace: gcp
#spec:
#
#  # Mount path of the secrets backend
#  mount: gcp
#  namespace: us-west-org
#  # Path to the secret
#  path: roleset/${PROJECT_ID}-viewer-token/token
#
#  # Where to store the secrets, VSO will create the secret
#  destination:
#    create: true
#    name: vso-gcp-token
#
##  # Restart these pods when secrets rotated
#  rolloutRestartTargets:
#  - kind: Deployment
#    name: gcp-app
##
#  # Name of the CRD to authenticate to Vault
#  vaultAuthRef: gcp-dynamic-auth
