apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-db-demo
  namespace: dynamic-app
spec:
  # Mount path of the secrets backend
  mount: db
  namespace: tn001
  # Path to the secret
  path: creds/dev-postgres

  # Where to store the secrets, end user will create the secret
  destination:
    create: true
    name: vso-db-demo

#  # Restart these pods when secrets rotated
#  rolloutRestartTargets:
#  - kind: Deployment
#    name: dynamic-app

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: dynamic-auth