apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: vso-pki-demo
  namespace: dynamic-app
spec:
  vaultAuthRef: dynamic-auth
  namespace: tn001
  mount: pki
  role: example-dot-com
  commonName: test.example.com
  format: pem
#  revoke: true
#  clear: true
  destination:
    create: true
    name: vso-pki-demo
    type: kubernetes.io/tls
    transformation:
      excludeRaw: true
  rolloutRestartTargets:
  - kind: Deployment
    name: dynamic-app